name: build

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
      - '*.md'
  workflow_dispatch:

jobs:

  linuxXwindows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential g++-mingw-w64-x86-64-posix gcc-mingw-w64-x86-64-posix
          
    - name: windows mingw build
      run: |
        ./build.sh
        mkdir release
        cp build/*.exe release
        cp build/*.dll release
        zip -r release.zip release

    - name: build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: release

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        name: "release-${{ github.ref_name }}"
        tag_name: ${{ github.ref }}
        files: |
          release.zip